version = 0.1
[default.deploy.parameters]
stack_name = "amazon-eventbridge-producer-consumer"
resolve_s3 = true
s3_prefix = "amazon-eventbridge-producer-consumer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
